### ISSUE TITLE
env file config

### ISSUE THREAD

**Issue by DoctusHartwald** [BittnerPierre/applied-ai-rag-assistant#3]
Hello Pierre, 

Can you please specify what are is needed in env. file (locally variable) to make it work ? 

Thanks & regards

**Comment by BittnerPierre** [comment]
Hello @DoctusHartwald ,

Thank you for your message. I've added some information regarding .env on the README.md. I've also removed a dependency in the code that used to force a langsmith account. 

I hope it will clarify the setup.

Thank you,
Pierre
