### ISSUE TITLE
Unable to find installation candidates for torch (2.3.1)

### ISSUE THREAD

**Issue by linaia** [BittnerPierre/applied-ai-rag-assistant#8]
Sous osx 14.5,
% python -V
Python 3.11.7
% poetry install

```
....
- Installing torch (2.3.1): Failed

  RuntimeError

  Unable to find installation candidates for torch (2.3.1)

  at venv/lib/python3.11/site-packages/poetry/installation/chooser.py:74 in choose_for
       70│
       71│             links.append(link)
       72│
       73│         if not links:
    →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       75│
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       78│

Cannot install torch.
```

https://github.com/python-poetry/poetry/issues/8917 
 j'ai forcé la version torch = "2.1.2" dans pyproject.toml, et ça passe

% poetry env use 3.11 
% poetry install

**Comment by BittnerPierre** [comment]
Hello linaia, 
Darwin 14.5 here with Python 3.10.12 & torch  2.3.1 running just fine.
Running fine also on Python 3.11.9 on Debian.
I'm considering this is a local python deployment issue.
Thanks for your contribution.

**Comment by BittnerPierre** [comment]
One colleague is having the same issue. He have python 3.11.x installed also. Forced torch to "2.1.2" version make it works. Thx.
